//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension MatreshkaAPI.AuthAPI {

    /** Авторизация Apple */
    public enum AuthByApple {

        public static let service = APIService<Response>(id: "authByApple", tag: "Auth API", method: "POST", path: "/api/v1/auth/apple", hasBody: true, securityRequirements: [])

        public final class Request: APIRequest<Response> {

            public var body: AppleAuthRequest

            public init(body: AppleAuthRequest, encoder: RequestEncoder? = nil) {
                self.body = body
                super.init(service: AuthByApple.service) { defaultEncoder in
                    return try (encoder ?? defaultEncoder).encode(body)
                }
            }
        }

        public enum Response: APIResponseValue, CustomStringConvertible, CustomDebugStringConvertible {
            public typealias SuccessType = AuthResponse

            /** OK */
            case status200(AuthResponse)

            public var success: AuthResponse? {
                switch self {
                case .status200(let response): return response
                }
            }

            public var response: Any {
                switch self {
                case .status200(let response): return response
                }
            }

            public var statusCode: Int {
                switch self {
                case .status200: return 200
                }
            }

            public var successful: Bool {
                switch self {
                case .status200: return true
                }
            }

            public init(statusCode: Int, data: Data, decoder: ResponseDecoder) throws {
                switch statusCode {
                case 200: self = try .status200(decoder.decode(AuthResponse.self, from: data))
                default: throw APIClientError.unexpectedStatusCode(statusCode: statusCode, data: data)
                }
            }

            public var description: String {
                return "\(statusCode) \(successful ? "success" : "failure")"
            }

            public var debugDescription: String {
                var string = description
                let responseString = "\(response)"
                if responseString != "()" {
                    string += "\n\(responseString)"
                }
                return string
            }
        }
    }
}
