//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension MatreshkaAPI.UserAPI {

    /** Проверка существования пользователя по почте */
    public enum ExistsByEmail {

        public static let service = APIService<Response>(id: "existsByEmail", tag: "User API", method: "GET", path: "/api/v1/user/email-exists/{email}", hasBody: false, securityRequirements: [SecurityRequirement(type: "Bearer", scopes: [])])

        public final class Request: APIRequest<Response> {

            public struct Options {

                public var email: String

                public init(email: String) {
                    self.email = email
                }
            }

            public var options: Options

            public init(options: Options) {
                self.options = options
                super.init(service: ExistsByEmail.service)
            }

            /// convenience initialiser so an Option doesn't have to be created
            public convenience init(email: String) {
                let options = Options(email: email)
                self.init(options: options)
            }

            public override var path: String {
                return super.path.replacingOccurrences(of: "{" + "email" + "}", with: "\(self.options.email)")
            }
        }

        public enum Response: APIResponseValue, CustomStringConvertible, CustomDebugStringConvertible {
            public typealias SuccessType = Bool

            /** OK */
            case status200(Bool)

            public var success: Bool? {
                switch self {
                case .status200(let response): return response
                }
            }

            public var response: Any {
                switch self {
                case .status200(let response): return response
                }
            }

            public var statusCode: Int {
                switch self {
                case .status200: return 200
                }
            }

            public var successful: Bool {
                switch self {
                case .status200: return true
                }
            }

            public init(statusCode: Int, data: Data, decoder: ResponseDecoder) throws {
                switch statusCode {
                case 200: self = try .status200(decoder.decode(Bool.self, from: data))
                default: throw APIClientError.unexpectedStatusCode(statusCode: statusCode, data: data)
                }
            }

            public var description: String {
                return "\(statusCode) \(successful ? "success" : "failure")"
            }

            public var debugDescription: String {
                var string = description
                let responseString = "\(response)"
                if responseString != "()" {
                    string += "\n\(responseString)"
                }
                return string
            }
        }
    }
}
