//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class AdminAuthRequest: APIModel {

    public var login: String?

    public var password: String?

    public init(login: String? = nil, password: String? = nil) {
        self.login = login
        self.password = password
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        login = try container.decodeIfPresent("login")
        password = try container.decodeIfPresent("password")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(login, forKey: "login")
        try container.encodeIfPresent(password, forKey: "password")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? AdminAuthRequest else { return false }
      guard self.login == object.login else { return false }
      guard self.password == object.password else { return false }
      return true
    }

    public static func == (lhs: AdminAuthRequest, rhs: AdminAuthRequest) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
