//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class AdminDTO: APIModel {

    public var id: ID?

    public var login: String?

    public init(id: ID? = nil, login: String? = nil) {
        self.id = id
        self.login = login
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        id = try container.decodeIfPresent("id")
        login = try container.decodeIfPresent("login")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(id, forKey: "id")
        try container.encodeIfPresent(login, forKey: "login")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? AdminDTO else { return false }
      guard self.id == object.id else { return false }
      guard self.login == object.login else { return false }
      return true
    }

    public static func == (lhs: AdminDTO, rhs: AdminDTO) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
