//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class AnonymousUserDTO: APIModel {

    public var createdAt: DateTime?

    public var deviceId: String?

    public var downloaded: Int?

    public var id: ID?

    public var type: String?

    public var uploaded: Int?

    public init(createdAt: DateTime? = nil, deviceId: String? = nil, downloaded: Int? = nil, id: ID? = nil, type: String? = nil, uploaded: Int? = nil) {
        self.createdAt = createdAt
        self.deviceId = deviceId
        self.downloaded = downloaded
        self.id = id
        self.type = type
        self.uploaded = uploaded
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        createdAt = try container.decodeIfPresent("createdAt")
        deviceId = try container.decodeIfPresent("deviceId")
        downloaded = try container.decodeIfPresent("downloaded")
        id = try container.decodeIfPresent("id")
        type = try container.decodeIfPresent("type")
        uploaded = try container.decodeIfPresent("uploaded")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(createdAt, forKey: "createdAt")
        try container.encodeIfPresent(deviceId, forKey: "deviceId")
        try container.encodeIfPresent(downloaded, forKey: "downloaded")
        try container.encodeIfPresent(id, forKey: "id")
        try container.encodeIfPresent(type, forKey: "type")
        try container.encodeIfPresent(uploaded, forKey: "uploaded")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? AnonymousUserDTO else { return false }
      guard self.createdAt == object.createdAt else { return false }
      guard self.deviceId == object.deviceId else { return false }
      guard self.downloaded == object.downloaded else { return false }
      guard self.id == object.id else { return false }
      guard self.type == object.type else { return false }
      guard self.uploaded == object.uploaded else { return false }
      return true
    }

    public static func == (lhs: AnonymousUserDTO, rhs: AnonymousUserDTO) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
