//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class AppleHookRequest: APIModel {

    public var signedPayload: String?

    public init(signedPayload: String? = nil) {
        self.signedPayload = signedPayload
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        signedPayload = try container.decodeIfPresent("signedPayload")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(signedPayload, forKey: "signedPayload")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? AppleHookRequest else { return false }
      guard self.signedPayload == object.signedPayload else { return false }
      return true
    }

    public static func == (lhs: AppleHookRequest, rhs: AppleHookRequest) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
