//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class BuyByBalanceRequest: APIModel {

    public var tariffId: ID

    public init(tariffId: ID) {
        self.tariffId = tariffId
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        tariffId = try container.decode("tariffId")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encode(tariffId, forKey: "tariffId")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? BuyByBalanceRequest else { return false }
      guard self.tariffId == object.tariffId else { return false }
      return true
    }

    public static func == (lhs: BuyByBalanceRequest, rhs: BuyByBalanceRequest) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
