//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class BuySubRequest: APIModel {

    public var receipt: String

    public init(receipt: String) {
        self.receipt = receipt
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        receipt = try container.decode("receipt")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encode(receipt, forKey: "receipt")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? BuySubRequest else { return false }
      guard self.receipt == object.receipt else { return false }
      return true
    }

    public static func == (lhs: BuySubRequest, rhs: BuySubRequest) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
