//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class CleanDevicesRequest: APIModel {

    public var nowDeviceId: String?

    public init(nowDeviceId: String? = nil) {
        self.nowDeviceId = nowDeviceId
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        nowDeviceId = try container.decodeIfPresent("nowDeviceId")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(nowDeviceId, forKey: "nowDeviceId")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? CleanDevicesRequest else { return false }
      guard self.nowDeviceId == object.nowDeviceId else { return false }
      return true
    }

    public static func == (lhs: CleanDevicesRequest, rhs: CleanDevicesRequest) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
