//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class CreateReviewRequest: APIModel {

    public var profile: File?

    public var result: File?

    public init(profile: File? = nil, result: File? = nil) {
        self.profile = profile
        self.result = result
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        profile = try container.decodeIfPresent("profile")
        result = try container.decodeIfPresent("result")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(profile, forKey: "profile")
        try container.encodeIfPresent(result, forKey: "result")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? CreateReviewRequest else { return false }
      guard self.profile == object.profile else { return false }
      guard self.result == object.result else { return false }
      return true
    }

    public static func == (lhs: CreateReviewRequest, rhs: CreateReviewRequest) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
