//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class EditWithdrawRequest: APIModel {

    public enum State: String, Codable, Equatable, CaseIterable {
        case new = "NEW"
        case executed = "EXECUTED"
        case cancelled = "CANCELLED"
    }

    public var withdrawId: ID

    public var state: State?

    public init(withdrawId: ID, state: State? = nil) {
        self.withdrawId = withdrawId
        self.state = state
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        withdrawId = try container.decode("withdrawId")
        state = try container.decodeIfPresent("state")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encode(withdrawId, forKey: "withdrawId")
        try container.encodeIfPresent(state, forKey: "state")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? EditWithdrawRequest else { return false }
      guard self.withdrawId == object.withdrawId else { return false }
      guard self.state == object.state else { return false }
      return true
    }

    public static func == (lhs: EditWithdrawRequest, rhs: EditWithdrawRequest) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
