//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class EmailAuthRequest: APIModel {

    public var deviceId: String

    public var verificationId: ID

    public init(deviceId: String, verificationId: ID) {
        self.deviceId = deviceId
        self.verificationId = verificationId
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        deviceId = try container.decode("deviceId")
        verificationId = try container.decode("verificationId")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encode(deviceId, forKey: "deviceId")
        try container.encode(verificationId, forKey: "verificationId")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? EmailAuthRequest else { return false }
      guard self.deviceId == object.deviceId else { return false }
      guard self.verificationId == object.verificationId else { return false }
      return true
    }

    public static func == (lhs: EmailAuthRequest, rhs: EmailAuthRequest) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
