//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class Environment: APIModel {

    public var activeProfiles: [String]?

    public var defaultProfiles: [String]?

    public init(activeProfiles: [String]? = nil, defaultProfiles: [String]? = nil) {
        self.activeProfiles = activeProfiles
        self.defaultProfiles = defaultProfiles
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        activeProfiles = try container.decodeArrayIfPresent("activeProfiles")
        defaultProfiles = try container.decodeArrayIfPresent("defaultProfiles")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(activeProfiles, forKey: "activeProfiles")
        try container.encodeIfPresent(defaultProfiles, forKey: "defaultProfiles")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? Environment else { return false }
      guard self.activeProfiles == object.activeProfiles else { return false }
      guard self.defaultProfiles == object.defaultProfiles else { return false }
      return true
    }

    public static func == (lhs: Environment, rhs: Environment) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
