//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class InitAnonymousUserRequest: APIModel {

    public var deviceId: String

    public init(deviceId: String) {
        self.deviceId = deviceId
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        deviceId = try container.decode("deviceId")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encode(deviceId, forKey: "deviceId")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? InitAnonymousUserRequest else { return false }
      guard self.deviceId == object.deviceId else { return false }
      return true
    }

    public static func == (lhs: InitAnonymousUserRequest, rhs: InitAnonymousUserRequest) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
