//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class SubmitEmailVerificationRequest: APIModel {

    public var code: String

    public var verificationId: ID

    public init(code: String, verificationId: ID) {
        self.code = code
        self.verificationId = verificationId
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        code = try container.decode("code")
        verificationId = try container.decode("verificationId")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encode(code, forKey: "code")
        try container.encode(verificationId, forKey: "verificationId")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? SubmitEmailVerificationRequest else { return false }
      guard self.code == object.code else { return false }
      guard self.verificationId == object.verificationId else { return false }
      return true
    }

    public static func == (lhs: SubmitEmailVerificationRequest, rhs: SubmitEmailVerificationRequest) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
