//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class UserTokenDTO: APIModel {

    public var id: ID?

    public var token: String?

    public init(id: ID? = nil, token: String? = nil) {
        self.id = id
        self.token = token
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        id = try container.decodeIfPresent("id")
        token = try container.decodeIfPresent("token")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(id, forKey: "id")
        try container.encodeIfPresent(token, forKey: "token")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? UserTokenDTO else { return false }
      guard self.id == object.id else { return false }
      guard self.token == object.token else { return false }
      return true
    }

    public static func == (lhs: UserTokenDTO, rhs: UserTokenDTO) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
