//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class UserStatisticResponse: APIModel {

    public var counts: [UserStatisticItem]?

    public init(counts: [UserStatisticItem]? = nil) {
        self.counts = counts
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        counts = try container.decodeArrayIfPresent("counts")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(counts, forKey: "counts")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? UserStatisticResponse else { return false }
      guard self.counts == object.counts else { return false }
      return true
    }

    public static func == (lhs: UserStatisticResponse, rhs: UserStatisticResponse) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
