//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class UserStatisticItem: APIModel {

    public var count: Int?

    public var date: String?

    public init(count: Int? = nil, date: String? = nil) {
        self.count = count
        self.date = date
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        count = try container.decodeIfPresent("count")
        date = try container.decodeIfPresent("date")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(count, forKey: "count")
        try container.encodeIfPresent(date, forKey: "date")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? UserStatisticItem else { return false }
      guard self.count == object.count else { return false }
      guard self.date == object.date else { return false }
      return true
    }

    public static func == (lhs: UserStatisticItem, rhs: UserStatisticItem) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
