//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

/** MatreshkaVPN API documentation */
public struct MatreshkaAPI {

    /// Whether to discard any errors when decoding optional properties
    public static var safeOptionalDecoding = false

    /// Whether to remove invalid elements instead of throwing when decoding arrays
    public static var safeArrayDecoding = false

    /// Used to encode Dates when uses as string params
    public static var dateEncodingFormatter = DateFormatter(formatString: "yyyy-MM-dd'T'HH:mm:ssZZZZZ",
                                                            locale: Locale(identifier: "en_US_POSIX"),
                                                            calendar: Calendar(identifier: .gregorian))

    public static let version = "1.0"

    public enum AbstractAPI {}
    public enum AdminPushAPI {}
    public enum AdminReviewAPI {}
    public enum AdminServerAPI {}
    public enum AdminStatisticAPI {}
    public enum AdminSystemAPI {}
    public enum AdminTariffAPI {}
    public enum AdminTariffAPIV2 {}
    public enum AdminTicketAPI {}
    public enum AdminUpdateAPI {}
    public enum AdminUserAPI {}
    public enum AdminWithdrawAPI {}
    public enum AdminAPI {}
    public enum AppleAPI {}
    public enum AuthAPI {}
    public enum BillingAPI {}
    public enum BillingAPIV2 {}
    public enum ReviewAPI {}
    public enum ServerAPI {}
    public enum SubscriptionAPI {}
    public enum SystemAPI {}
    public enum TariffAPI {}
    public enum TariffAPIV2 {}
    public enum TicketAPI {}
    public enum UpdateAPI {}
    public enum UserAPI {}

    public enum Server {

        /** Generated server url **/
        public static let main = MatreshkaHelper.domain
    }
}
