//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension MatreshkaAPI.ServerAPI {

    /** Обновление данных */
    public enum UpdateServerStatus1 {

        public static let service = APIService<Response>(id: "updateServerStatus_1", tag: "Server API", method: "GET", path: "/api/v1/server/server-data", hasBody: false, securityRequirements: [])

        public final class Request: APIRequest<Response> {

            public struct Options {

                public var serverIp: String

                public var nowClients: Int

                public var maxClients: Int

                public init(serverIp: String, nowClients: Int, maxClients: Int) {
                    self.serverIp = serverIp
                    self.nowClients = nowClients
                    self.maxClients = maxClients
                }
            }

            public var options: Options

            public init(options: Options) {
                self.options = options
                super.init(service: UpdateServerStatus1.service)
            }

            /// convenience initialiser so an Option doesn't have to be created
            public convenience init(serverIp: String, nowClients: Int, maxClients: Int) {
                let options = Options(serverIp: serverIp, nowClients: nowClients, maxClients: maxClients)
                self.init(options: options)
            }

            public override var queryParameters: [String: Any] {
                var params: [String: Any] = [:]
                params["serverIp"] = options.serverIp
                params["nowClients"] = options.nowClients
                params["maxClients"] = options.maxClients
                return params
            }
        }

        public enum Response: APIResponseValue, CustomStringConvertible, CustomDebugStringConvertible {
            public typealias SuccessType = String

            /** OK */
            case status200(String)

            public var success: String? {
                switch self {
                case .status200(let response): return response
                }
            }

            public var response: Any {
                switch self {
                case .status200(let response): return response
                }
            }

            public var statusCode: Int {
                switch self {
                case .status200: return 200
                }
            }

            public var successful: Bool {
                switch self {
                case .status200: return true
                }
            }

            public init(statusCode: Int, data: Data, decoder: ResponseDecoder) throws {
                switch statusCode {
                case 200: self = try .status200(decoder.decode(String.self, from: data))
                default: throw APIClientError.unexpectedStatusCode(statusCode: statusCode, data: data)
                }
            }

            public var description: String {
                return "\(statusCode) \(successful ? "success" : "failure")"
            }

            public var debugDescription: String {
                var string = description
                let responseString = "\(response)"
                if responseString != "()" {
                    string += "\n\(responseString)"
                }
                return string
            }
        }
    }
}
